"use client";

import { useMemo, useState } from "react";
import { ChevronLeft, Play, ShieldCheck, ShieldOff } from "lucide-react";
import { setConceptApprovalAction, setConceptVideoApprovalAction, setPassageApprovalAction } from "@/app/(admin)/admin/actions";
import { AdminForm } from "@/components/admin/admin-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatTimestamp, parseVideoUrl, playerSrc } from "@/lib/video";

type Passage = { id: string; text: string; reviewText: string | null; approved: boolean; humanReviewRequired: boolean; version: number; sourceReference: string; startSecond: number | null; endSecond: number | null };
export type ReviewConcept = { id: string; title: string; videoUrl: string | null; startSecond: number | null; endSecond: number | null; videoApproved: boolean; passages: Passage[] };
type Filter = "ALL" | "UNAPPROVED" | "APPROVED" | "REVIEW";

function PassageCard({ concept, passage }: { concept: ReviewConcept; passage: Passage }) {
  return <article className="rounded-xl border border-line bg-paper/60 p-4" data-testid="review-workspace-passage">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-2"><Badge tone="ink">{concept.title}</Badge><Badge tone={passage.approved ? "success" : "warning"} icon={passage.approved ? <ShieldCheck className="size-3" aria-hidden /> : <ShieldOff className="size-3" aria-hidden />}>{passage.approved ? "النص معتمد" : "النص بانتظار الاعتماد"}</Badge>{passage.humanReviewRequired ? <Badge tone="warning">يحتاج مراجعة بشرية</Badge> : null}<Badge tone="neutral">الإصدار {passage.version}</Badge></div><AdminForm action={setPassageApprovalAction} submitLabel={passage.approved ? "إلغاء اعتماد النص" : "اعتماد النص"} variant={passage.approved ? "ghost" : "sage"} size="sm" inline><input type="hidden" name="id" value={passage.id} /><input type="hidden" name="approved" value={passage.approved ? "false" : "true"} /></AdminForm></div>
    <p className="mt-3 text-caption font-medium text-gold-ink">reviewText — النص المراجَع</p><p className="mt-1 font-naskh text-card leading-9 text-ink-dark">{passage.reviewText ?? passage.text}</p><p className="mt-3 text-caption text-muted">{passage.sourceReference}{passage.startSecond != null ? <span dir="ltr"> · {formatTimestamp(passage.startSecond)}{passage.endSecond != null ? ` → ${formatTimestamp(passage.endSecond)}` : ""}</span> : null}</p>
  </article>;
}

export function ConceptReviewWorkspace({ concepts, initialConceptId }: { concepts: ReviewConcept[]; initialConceptId?: string }) {
  const [index, setIndex] = useState(Math.max(0, concepts.findIndex((c) => c.id === initialConceptId)));
  const [run, setRun] = useState(0); const [all, setAll] = useState(false); const [search, setSearch] = useState(""); const [filter, setFilter] = useState<Filter>("ALL");
  const concept = concepts[index];
  const src = useMemo(() => { if (!concept?.videoUrl || concept.startSecond == null || !parseVideoUrl(concept.videoUrl)) return null; const base = playerSrc({ url: concept.videoUrl, startSecond: concept.startSecond, endSecond: concept.endSecond }); return run && base?.includes("youtube-nocookie.com") ? `${base}&autoplay=1` : base; }, [concept, run]);
  const shown = useMemo(() => (all ? concepts : [concept]).filter(Boolean).map((c) => ({ ...c!, passages: c!.passages.filter((p) => { const q = search.trim().toLocaleLowerCase(); const found = !q || `${c!.title} ${p.text} ${p.reviewText ?? ""}`.toLocaleLowerCase().includes(q); return found && (filter === "ALL" || filter === "APPROVED" && p.approved || filter === "UNAPPROVED" && !p.approved || filter === "REVIEW" && p.humanReviewRequired); }) })).filter((c) => c.passages.length), [all, concept, concepts, filter, search]);
  if (!concept) return null;
  const select = (next: number) => { setIndex(next); setRun(0); setAll(false); };
  return <div className="space-y-5" data-testid="admin-review-workspace">
    <div className="flex flex-wrap items-end gap-3"><div className="min-w-0 flex-1"><label htmlFor="review-concept" className="mb-1.5 block text-small font-medium text-ink">المفهوم المراد التحقق منه</label><select id="review-concept" value={concept.id} onChange={(e) => select(concepts.findIndex((c) => c.id === e.target.value))} className="h-11 w-full rounded-lg border border-line-strong bg-white px-3.5 text-body text-text focus:outline-none focus:shadow-[var(--shadow-focus)]">{concepts.map((c) => <option key={c.id} value={c.id}>{c.title}</option>)}</select></div><Button type="button" variant="secondary" disabled={!src} onClick={() => setRun((v) => v + 1)} icon={<Play className="size-4" aria-hidden />}>تشغيل من بداية المقطع</Button></div>
    {src ? <div className="overflow-hidden rounded-xl border border-line bg-ink-dark"><iframe key={`${concept.id}-${run}`} src={src} title={`فيديو التحقق — ${concept.title}`} className="aspect-video w-full" allow="accelerometer; autoplay; encrypted-media; picture-in-picture; fullscreen" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen data-testid="admin-video-player" /></div> : <p className="rounded-lg border border-dashed border-line-strong px-4 py-8 text-center text-small text-muted">لا يوجد فيديو أو توقيت صالح مسجّل لهذا المفهوم.</p>}
    <div className="flex flex-wrap items-center gap-2 rounded-xl border border-line bg-surface p-3"><Badge tone="ink">{concept.title}</Badge><span dir="ltr" className="text-small text-ink tabular-nums">{concept.startSecond != null ? formatTimestamp(concept.startSecond) : "—"} → {concept.endSecond != null ? formatTimestamp(concept.endSecond) : "—"}</span><Badge tone={concept.videoApproved ? "success" : "warning"}>{concept.videoApproved ? "التوقيت معتمد" : "التوقيت بانتظار الاعتماد"}</Badge><AdminForm action={setConceptVideoApprovalAction} submitLabel={concept.videoApproved ? "إلغاء اعتماد التوقيت" : "اعتماد التوقيت"} variant={concept.videoApproved ? "ghost" : "sage"} size="sm" inline><input type="hidden" name="id" value={concept.id} /><input type="hidden" name="approved" value={concept.videoApproved ? "false" : "true"} /></AdminForm></div>
    <div className="flex gap-2 border-b border-line"><button type="button" onClick={() => setAll(false)} className={!all ? "border-b-2 border-ink px-3 py-2 text-small font-semibold" : "px-3 py-2 text-small text-muted"}>المفهوم الحالي</button><button type="button" onClick={() => setAll(true)} className={all ? "border-b-2 border-ink px-3 py-2 text-small font-semibold" : "px-3 py-2 text-small text-muted"}>جميع النصوص</button></div>
    {all ? <div className="space-y-3 rounded-xl border border-line bg-surface p-3"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="ابحث في نصوص الدرس..." className="h-10 w-full rounded-lg border border-line-strong bg-white px-3 text-small outline-none focus:shadow-[var(--shadow-focus)]" /><div className="flex flex-wrap gap-2">{([ ["ALL", "الكل"], ["UNAPPROVED", "غير معتمد"], ["APPROVED", "معتمد"], ["REVIEW", "يحتاج مراجعة"] ] as const).map(([value, label]) => <button type="button" key={value} onClick={() => setFilter(value)} className={filter === value ? "rounded-full bg-ink px-3 py-1 text-caption text-surface" : "rounded-full border border-line px-3 py-1 text-caption text-muted"}>{label}</button>)}</div></div> : null}
    <div className="space-y-4">{shown.length ? shown.map((c) => <div key={c.id} className="space-y-3">{all ? <h3 className="text-small font-semibold text-ink">{c.title}</h3> : null}{c.passages.map((p) => <PassageCard key={p.id} concept={c} passage={p} />)}</div>) : <p className="rounded-lg border border-dashed border-line-strong px-4 py-8 text-center text-small text-muted">{all ? "لا توجد نصوص تطابق البحث أو الفلتر." : "لا يوجد نص مرتبط بهذا المفهوم."}</p>}</div>
    <div className="flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4"><Button type="button" variant="secondary" size="sm" disabled={index === 0} onClick={() => select(index - 1)} icon={<ChevronLeft className="size-4 rotate-180" aria-hidden />}>المفهوم السابق</Button><span className="text-small text-muted">المفهوم {index + 1} من {concepts.length}</span><Button type="button" variant="secondary" size="sm" disabled={index === concepts.length - 1} onClick={() => select(index + 1)} icon={<ChevronLeft className="size-4" aria-hidden />}>المفهوم التالي</Button></div>
    <AdminForm action={setConceptApprovalAction} submitLabel="اعتماد المفهوم وفق المراجعة الحالية" variant="sage" size="sm" inline><input type="hidden" name="id" value={concept.id} /><input type="hidden" name="approved" value="true" /></AdminForm>
  </div>;
}
