import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

/**
 * «اقتباس اليوم» is human-curated: nothing is generated by AI. A quote appears on the student home
 * only after a person approves it, and only with a named author and source.
 *
 *   npm run quotes -- list
 *   npm run quotes -- add "<text>" "<author>" "<source>"      (added as NOT approved)
 *   npm run quotes -- approve <id> <reviewer>
 *   npm run quotes -- unapprove <id>
 */
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }) });

async function main() {
  const [command, ...args] = process.argv.slice(2);
  if (command === "list") {
    for (const q of await prisma.quote.findMany({ orderBy: { createdAt: "asc" } })) {
      console.log(`${q.approved ? "✔ approved " : "… pending  "} ${q.id}  «${q.text}» — ${q.author}، ${q.source}`);
    }
  } else if (command === "add") {
    const [text, author, source] = args.map((a) => a?.trim());
    if (!text || !author || !source) throw new Error('Usage: add "<text>" "<author>" "<source>" — all three are required');
    const q = await prisma.quote.create({ data: { text, author, source } });
    console.log(`Added ${q.id} (pending). Approve it after checking the wording against the source.`);
  } else if (command === "approve") {
    const [id, reviewer] = args;
    if (!id || !reviewer) throw new Error("Usage: approve <id> <reviewer>");
    await prisma.quote.update({ where: { id }, data: { approved: true, approvedAt: new Date(), approvedById: reviewer } });
    console.log(`Approved ${id} by ${reviewer}.`);
  } else if (command === "unapprove") {
    if (!args[0]) throw new Error("Usage: unapprove <id>");
    await prisma.quote.update({ where: { id: args[0] }, data: { approved: false, approvedAt: null, approvedById: null } });
    console.log(`Unapproved ${args[0]}.`);
  } else {
    throw new Error("Usage: npm run quotes -- list | add | approve | unapprove");
  }
}

main()
  .catch((e) => {
    console.error(e instanceof Error ? e.message : e);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
